version: "3.6"

services:
    frontend:
        build:
            context: . 
            dockerfile: _docker/frontend/DockerFile
        image: apteka
    
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
